controllers/LoanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Loan;
use yii\web\Controller;
use app\models\LoanSearch;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

/**
 * LoanController implements the CRUD actions for Loan model.
 *
 * @package app\controllers
 * @author Abdelatif Zache <zacheabdelatif@outlook.de>
 */
class LoanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Loan::find(),
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC
                ]
            ]
        ]);

        $searchModel = new LoanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Loan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Loan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param int $user_id User id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionCreate($user_id)
    {
        $model = new Loan();
        $user = User::findOneOrFail($user_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('message', 'Insert Successfully');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'user_id' => $user->getAttribute('id'),
        ]);
    }

    /**
     * Updates an existing Loan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('message', 'Insert Successfully');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'user_id' => $model->user->id,
        ]);
    }

    /**
     * Deletes an existing Loan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->getSession()->setFlash('message', 'Delete Successfully');

        return $this->redirect(['index']);
    }

    /**
     * Finds the Loan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Loan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse'
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-inverse navbar-nav navbar-left'],
        'encodeLabels' => false,
        'items' => [
            ['label' => 'Klienditeenindus'],
            ['label' => "<span class='glyphicon glyphicon-phone'></span> 1715"],
            ['label' => "<span class='glyphicon glyphicon-time'></span> E-P 9.00-21.00"],
        ],
    ]);

    echo Nav::widget([
        'options' => ['class' => 'navbar-inverse navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
            Yii::$app->user->isGuest ? ((
                '<li>'
                . Html::beginForm(['/site/login'], 'post')
                . Html::submitButton(
                    'Login',
                    ['class' => 'button-orange']
                )
                . Html::endForm()
                . '</li>'
            )
                
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'button-orange']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-inverse navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
            '<li>'.Html::a("Tere, Kaupo Kasutaja", ['/']).'</li>',
            
        ],
        
    ]);
    NavBar::end();
    ?>
    <?php
    NavBar::begin([]); 
        
    echo Nav::widget([
        'options' => ['class' => 'navbar navbar-nav navbar-left' ],
        'encodeLabels' => false,
        'items' => [
             ['label'=>Html::img('https://www.creditstar.ee/themes/creditstar_ee//img/header-logo.png', ['alt'=>'','class'=>'headerLogo'])],
            ['label'=>'Loans<span class="glyphicon glyphicon-chevron-right orng-col"></span>','url' =>'https://www.creditstar.ee/est/site/laenud'],
            ['label'=>'Need help?<span class="glyphicon glyphicon-chevron-right orng-col"></span>','url'=>'https://www.creditstar.ee/est/site/help'],
            ['label'=>'About us<span class="glyphicon glyphicon-chevron-right orng-col"></span>', 'url' => 'https://www.creditstar.ee/est/site/firmast'],
            ['label'=>'Responsible Lending<span class="glyphicon glyphicon-chevron-right orng-col"></span>', 'url' => 'https://www.creditstar.ee/est/site/vastutustundlik'],
        ],
    ]);
    echo Nav::widget([
        'options' => [
            'class'=>'navbar text-small text-right navbar-nav navbar-right'
        ],
        'encodeLabels' => false,
        'items' => [
            ['label'=>'По-русски','url'=>['/'],'class'=>'text-small'],
        ],

    ]);

    NavBar::end();
    ?>
    <div class="navPills">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-xs-11 col-sm-11 col-md-11">
                    <ul class="nav nav-pills">
                        <li role="presentation"><?php echo Html::a("My Actions", ['/']);?></li>
                        <li role="presentation"><?php echo Html::a("Users", ['/user/index']);?></li>
                        <li role="presentation"><?php echo Html::a("Loans", ['/loan/index']);?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container creditstarContainer">
        <div class="corner-ribbon top-left sticky red shadow"><span class="ribbonIcon glyphicon glyphicon-share-alt"></span></div>

        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>