models/User.php
<?php

namespace app\models;

use app\components\validators\PersonalCodeValidator;
use DateTime;
use yii\db\ActiveRecord;
use yii\web\NotFoundHttpException;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property int $personal_code
 * @property int $phone
 * @property bool $active
 * @property bool $dead
 *
 * @property Loan $loan
 */
class User extends ActiveRecord implements IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'active' => 'Status',
            'dead' => 'Vital Status',
            'lang' => 'Language',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            // The first_name, last_name, email and personal_code attributes are required
            [['first_name', 'last_name', 'email', 'personal_code', 'phone', 'active', 'dead'], 'required'],

            // The first_name, last_name and lang attribute should be string
            [['first_name', 'last_name', 'lang'], 'string'],

            // The personal_code and phone attribute should be integer
            [['personal_code', 'phone'], 'integer'],

            // The active and dead attribute should be boolean
            [['active', 'dead'], 'boolean'],

            // The email attribute should be a valid email address
            [['email'], 'email'],

            ['personal_code', PersonalCodeValidator::className()]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * Get user birthday as Datetime object
     *
     * @return Datetime user birthday
     * @throws \Exception
     */
    public function getBirthDate()
    {
        $year = substr($this->personal_code, 1, 2);
        $month = substr($this->personal_code, 3, 2);
        $day = substr($this->personal_code, 5, 2);
        $birthDate = new Datetime($year . '-' . $month . '-' . $day);
        return $birthDate;
    }

    /**
     * Get user birthday as Datetime object
     *
     * @return bool|\DateInterval user birthday
     * @throws \Exception
     */
    public function age()
    {
        $now = new DateTime();
        return $this->getBirthDate()->diff($now);
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoans()
    {
        return $this->hasMany(Loan::className(), ['user_id' => 'id']);
    }

    /**
     * @param integer $id
     * @return User|null
     * @throws NotFoundHttpException
     * @author Abdelatif Zache <zacheabdelatif@outlook.de>
     */
    public static function findOneOrFail($id)
    {
        $user = self::findOne($id);

        if ($user !== null) {
            return $user;
        }

        throw new NotFoundHttpException('User Not Found.');
    }

}

controllers/LoanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Loan;
use yii\web\Controller;
use app\models\LoanSearch;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

/**
 * LoanController implements the CRUD actions for Loan model.
 *
 * @package app\controllers
 * @author Abdelatif Zache <zacheabdelatif@outlook.de>
 */
class LoanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Loan::find(),
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC
                ]
            ]
        ]);

        $searchModel = new LoanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Loan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Loan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param int $user_id User id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionCreate($user_id)
    {
        $model = new Loan();
        $user = User::findOneOrFail($user_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('message', 'Insert Successfully');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'user_id' => $user->getAttribute('id'),
        ]);
    }

    /**
     * Updates an existing Loan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('message', 'Insert Successfully');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'user_id' => $model->user->id,
        ]);
    }

    /**
     * Deletes an existing Loan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->getSession()->setFlash('message', 'Delete Successfully');

        return $this->redirect(['index']);
    }

    /**
     * Finds the Loan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Loan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/UserController.php
<?php


namespace app\controllers;


use Yii;
use app\models\User;
use yii\web\Controller;
use app\models\UserSearch;
use yii\data\ActiveDataProvider;

/**
 * Class UserController
 *
 * @package app\controllers
 * @author Abdelatif Zache <zacheabdelatif@outlook.de>
 */
class UserController extends Controller
{

    /**
     * List of all users with pagination
     *
     * @access public
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC
                ]
            ]
        ]);

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);

    }


    /**
     * Create new User
     *
     * @access public
     * @return mixed
     */
    public function actionCreate()
    {
        $user_model = new User();

        $formData = Yii::$app->request->post();

        if ($user_model->load($formData) && $user_model->save()) {
            Yii::$app->getSession()->setFlash('message', 'Insert Successfully');
            return $this->redirect(['user/index']);
        } elseif ($user_model->load($formData)) {
            Yii::$app->getSession()->setFlash('message', 'Insert Failed');
        }

        return $this->render('create', [
            'model' => $user_model
        ]);
    }


    /**
     * View User
     *
     * @access public
     * @param integer $id
     * @return mixed
     * @throws yii\web\NotFoundHttpException
     */
    public function actionView($id)
    {
        $user_model = User::findOneOrFail($id);

        return $this->render('view', [
            'user_model' => $user_model
        ]);
    }

    /**
     * Update User
     *
     * @access public
     * @param integer $id
     * @return mixed
     * @throws yii\web\NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $user_model = User::findOneOrFail($id);

        if ($user_model->load(Yii::$app->request->post()) && $user_model->save()) {

            Yii::$app->getSession()->setFlash('message', 'Update Successfully');
            return $this->redirect(['user/index']);

        } elseif ($user_model->load(Yii::$app->request->post())) {

            Yii::$app->getSession()->setFlash('message', 'Insert Failed');

        }

        return $this->render('update', [
            'model' => $user_model
        ]);
    }

    /**
     * delete User
     *
     * @access public
     * @param integer $id
     * @return mixed
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $user_model = User::findOneOrFail($id)->delete();

        if ($user_model)
            Yii::$app->getSession()->setFlash('message', 'Delete Successfully');

        return $this->redirect(['user/index']);

    }

}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/** @var app\models\User $model */

?>

<div class="row">

    <?php $form = ActiveForm::begin([
        'id' => 'user-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-7\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]);
    ?>

    <?=
    $form->field($model, 'first_name')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput() ?>

    <?= $form->field($model, 'email')->input('email') ?>

    <?= $form->field($model, 'phone')->textInput() ?>

    <?= $form->field($model, 'personal_code')->textInput() ?>

    <?= $form->field($model, 'lang')->textInput() ?>

    <?= $form->field($model, 'active')->checkbox()->label('User is active.') ?>

    <?= $form->field($model, 'dead')->checkbox()->label('User is Dead.')?>

    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-1">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-success', 'name' => 'user-form']) ?>
        </div>
        <div class="col-lg-3">
            <?= Html::a('Back', Yii::$app->request->referrer ?: ['user/index'], ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'personal_code') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/** @var app\models\User $user_model */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['user/index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-create">

    <?php if (Yii::$app->session->hasFlash('message')): ?>
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?= Yii::$app->session->getFlash('message'); ?>
        </div>
    <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\grid\GridView;
use yii\widgets\LinkPager;

/** @var app\models\User $users */
/** @var yii\data\Pagination $pages */
/** @var app\models\UserSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'List of users';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-index">

    <?php if (Yii::$app->session->hasFlash('message')): ?>
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?= Yii::$app->session->getFlash('message'); ?>
        </div>
    <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <hr>
        <span><?= Html::a('Add User', ['/user/create'], ['class' => 'btn btn-primary pull-right']) ?></span>
        <a href="<?= yii::$app->homeUrl ?>" class="btn btn-default">Back</a> <hr>
        
    </div>
    <div class="row">
        <?php Pjax::begin(); ?>
        
        <?=

        GridView::widget([

            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'first_name',
                'last_name',
                'email',
                [
                    'attribute' => 'Birth Date',
                    'format' => 'raw',
                    'value' => function ($model) {
                        return $model->getBirthDate()->format('d M Y');
                    },
                ],
                [
                    'attribute' => 'Age',
                    'format' => 'raw',
                    'value' => function ($model) {
                        return $model->age()->y;
                    },
                ],
                'personal_code',
                'phone',
                'active:boolean',
                'dead:boolean',
                'lang',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{leadCreate} {leadView} {leadUpdate} {leadDelete}',
                    'buttons' => [
                        'leadCreate' => function ($url, $model) {
                            $url = Url::to(['loan/create', 'user_id' => $model->getAttribute('id')]);
                            return Html::a('Crate a Loan for user', $url, ['title' => 'view', 'class' => 'label label-success']);
                        },
                        'leadView' => function ($url, $model) {
                            $url = Url::to(['user/view', 'id' => $model->getAttribute('id')]);
                            return Html::a('View', $url, ['title' => 'view', 'class' => 'label label-primary']);
                        },
                        'leadUpdate' => function ($url, $model) {
                            $url = Url::to(['user/update', 'id' => $model->getAttribute('id')]);
                            return Html::a('Edit', $url, ['title' => 'update', 'class' => 'label label-default']);
                        },
                        'leadDelete' => function ($url, $model) {
                            $url = Url::to(['user/delete', 'id' => $model->getAttribute('id')]);
                            return Html::a('Delete', $url, [
                                'title' => 'delete',
                                'class' => 'label label-danger',
                                'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this user?'),
                                'data-method' => 'post',
                            ]);
                        },
                    ]],
            ],
        ]); ?>
        
        <?php Pjax::end(); ?>
        
        

    </div>

</div>

views/user/update.php
<?php

use yii\helpers\Html;

$this->title = 'Update User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['user/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-update">

    <?php if (Yii::$app->session->hasFlash('message')): ?>
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?= Yii::$app->session->getFlash('message'); ?>
        </div>
    <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;

/** @var app\models\User $user_model */

$this->title = 'View User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Name:
            <?=
            $user_model->getAttribute('first_name')
            . ' ' .
            $user_model->getAttribute('last_name')
            ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Email:
            <?= $user_model->getAttribute('email') ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Birth Date:
            <?= $user_model->getBirthDate()->format('d M Y') ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Age:
            <?= $user_model->age()->y ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Personal Code:
            <?= $user_model->getAttribute('personal_code') ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Phone:
            <?= $user_model->getAttribute('phone') ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Status:
            <?= $user_model->getAttribute('active') ? 'Active' : 'Inactive'; ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Vital Status:
            <?= $user_model->getAttribute('dead') ? 'Dead' : 'Alive'; ?>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Language:
            <?= $user_model->getAttribute('lang') ?>
        </li>
    </ul>
    <div class="row">
        <div class="col-lg-1">
            <?php Html::a('Add Loan', ['loan/create', 'user_id' => $user_model->getAttribute('id')], ['class' => 'btn btn-success']) ?>
        </div>
        <div class="col-lg-1">
            <?= Html::a('Edit', ['update', 'id' => $user_model->getAttribute('id')], ['class' => 'btn btn-default']) ?>
        </div>
        <div class="col-lg-3">
            <?= Html::a('Delete', ['delete', 'id' => $user_model->getAttribute('id')], ['class' => 'btn btn-danger']) ?>
        </div>

        <div class="col-lg-7">
            <?= Html::a('Back', ['user/index'], ['class' => 'btn btn-primary']) ?>
        </div>
    </div>


</div>